# Generated by Django 4.2 on 2023-05-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('email_id', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
