# Generated by Django 4.2 on 2023-05-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('client', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='New_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('client', models.CharField(max_length=250)),
                ('bill_date', models.CharField(max_length=250)),
                ('added_items', models.CharField(max_length=250)),
            ],
        ),
    ]
